#!/usr/bin/env python3
"""Commit and PR attribution: the project's settings, the commit-msg rewrite,
and the model that wrote the change.

    attribution.py settings <repo>
    attribution.py hook <message-file> <repo-or-empty> <dex-trailer>
    attribution.py model <router-file-or-empty> <transcript-root> <launch-dir> <conversation-id>

`settings` prints the normalized `## Attribution` block of `<repo>/.dex/dex.md`
as `key=value` lines. A missing file, section or key means the default, which
is today's behaviour. A malformed block or an unknown value is reported on
stderr and replaced by the default.

`hook` rewrites a commit message file in place for the project's mode: it
removes Claude attribution lines for `dex` and `none`, and the Dex trailer for
`none`. It only edits the part above git's scissors line, because everything
below it is the `git commit -v` diff, which git discards. It prints the mode,
the model trailer key and whether the message has any content, for the shell
caller that adds the trailers with `git interpret-trailers`.

`model` prints the model that produced the latest assistant turn, or nothing.
It reads the CCR router's session record when one is given, then the one
transcript file of the current conversation. It never lists or scans the
transcript directory, and it only reads.
"""

import importlib.util
import json
import os
import re
import sys
from pathlib import Path

MODES = ("dex", "claude", "both", "none")
DEFAULTS = {
    "attribution": "dex",
    "model_trailer": "",
    "pr_models": "false",
    "hooks": "true",
    "pr_template": "true",
}
BOOLEAN_KEYS = ("pr_models", "hooks", "pr_template")
TRUE_WORDS = ("true", "yes", "on", "1")
FALSE_WORDS = ("false", "no", "off", "0")
TRAILER_KEY = re.compile(r"^[A-Za-z0-9][A-Za-z0-9-]*$")
SCISSORS = re.compile(r"^\S -{24} >8 -{24}$")
CLAUDE_LINES = (
    re.compile(r"^\s*Co-Authored-By:\s*Claude\b.*$", re.I),
    re.compile(
        r".*(?:Generated with .*Claude Code|Generated by Claude(?: Code)?|"
        r"Created by Claude(?: Code)?|Authored(?: by| with) Claude(?: Code)?).*",
        re.I,
    ),
)
# Transcripts grow to hundreds of megabytes. The newest assistant turn is near
# the end, so the file is read backwards in chunks and the scan stops at the
# first match.
TAIL_CHUNK = 256 * 1024


def warn(message):
    print(f"dex: {message}", file=sys.stderr)


def contract_reader():
    source = Path(__file__).with_name("project-contract.py")
    spec = importlib.util.spec_from_file_location("dex_project_contract", source)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load {source}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def attribution_block(repo):
    """The `## Attribution` mapping, {} when absent, None when malformed."""
    if not repo:
        return {}
    contract = Path(repo) / ".dex" / "dex.md"
    try:
        text = contract.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return {}
    reader = contract_reader()
    lines = reader.section_lines(text, "Attribution")
    if lines is None:
        return {}
    body = reader.fenced_block(lines)
    if body is None:
        return {}
    return reader.parse_mapping(body)


def settings(repo):
    values = dict(DEFAULTS)
    block = attribution_block(repo)
    if block is None:
        warn(f"the '## Attribution' block in {repo}/.dex/dex.md is not a flat "
             "mapping; using the default attribution settings")
        return values
    mode = block.get("attribution")
    if isinstance(mode, str) and mode.strip():
        mode = mode.strip().lower()
        if mode in MODES:
            values["attribution"] = mode
        else:
            warn(f"unknown attribution mode '{mode}'; using 'dex'")
    trailer = block.get("model_trailer")
    if isinstance(trailer, str) and trailer.strip():
        trailer = trailer.strip()
        if trailer.lower() in FALSE_WORDS:
            pass
        elif TRAILER_KEY.match(trailer):
            values["model_trailer"] = trailer
        else:
            warn(f"model_trailer '{trailer}' is not a valid Git trailer key; "
                 "the model trailer is off")
    for key in BOOLEAN_KEYS:
        raw = block.get(key)
        if not isinstance(raw, str) or not raw.strip():
            continue
        word = raw.strip().lower()
        if word in TRUE_WORDS:
            values[key] = "true"
        elif word in FALSE_WORDS:
            values[key] = "false"
        else:
            warn(f"'{key}: {raw}' is not true or false; using {DEFAULTS[key]}")
    return values


def rewrite(message_file, mode, dex_trailer):
    """Strip attribution lines above the scissors line; report content."""
    path = Path(message_file)
    text = path.read_text(encoding="utf-8", errors="surrogateescape")
    lines = text.splitlines(keepends=True)
    cut = next((index for index, line in enumerate(lines)
                if SCISSORS.match(line.rstrip("\r\n"))), len(lines))
    head, tail = lines[:cut], lines[cut:]
    patterns = list(CLAUDE_LINES) if mode in ("dex", "none") else []
    if mode == "none" and dex_trailer:
        patterns.append(re.compile(r"^\s*" + re.escape(dex_trailer) + r"\s*$", re.I))
    kept = [line for line in head
            if not any(pattern.match(line.rstrip("\r\n")) for pattern in patterns)]
    if len(kept) != len(head):
        path.write_text("".join(kept + tail), encoding="utf-8", errors="surrogateescape")
    return any(line.strip() and not line.lstrip().startswith("#") for line in kept)


def tail_lines(handle, size):
    """Complete lines of a file, newest first, read backwards in chunks."""
    position = size
    partial = b""
    while position > 0:
        step = min(TAIL_CHUNK, position)
        position -= step
        handle.seek(position)
        chunk = handle.read(step) + partial
        pieces = chunk.split(b"\n")
        partial = pieces[0]
        for piece in reversed(pieces[1:]):
            if piece.strip():
                yield piece
    if partial.strip():
        yield partial


def transcript_model(transcript):
    """The model of the newest real assistant turn, or ''."""
    try:
        if os.path.islink(transcript) or not os.path.isfile(transcript):
            return ""
        with open(transcript, "rb") as handle:
            size = os.fstat(handle.fileno()).st_size
            for raw in tail_lines(handle, size):
                try:
                    row = json.loads(raw)
                except ValueError:
                    continue
                if not isinstance(row, dict) or row.get("type") != "assistant":
                    continue
                message = row.get("message")
                if not isinstance(message, dict) or not message.get("usage"):
                    continue
                model = message.get("model")
                if isinstance(model, str) and model and model != "<synthetic>":
                    return model
    except OSError:
        return ""
    return ""


def router_model(router_file):
    try:
        if os.path.islink(router_file) or not os.path.isfile(router_file):
            return ""
        with open(router_file, "r", encoding="utf-8") as handle:
            data = json.load(handle)
    except (OSError, ValueError):
        return ""
    model = data.get("current_model") if isinstance(data, dict) else None
    return model if isinstance(model, str) else ""


def transcript_path(root, launch_dir, conversation):
    """Claude Code keeps a session at projects/<launch dir>/<conversation>.jsonl,
    with every character of the launch dir that is not a letter or a digit
    replaced by '-' (the same rule as scripts/ccr/context.cjs)."""
    encoded = re.sub(r"[^A-Za-z0-9]", "-", launch_dir)
    return os.path.join(root, "projects", encoded, f"{conversation}.jsonl")


def model(router_file, root, launch_dir, conversation):
    found = router_model(router_file) if router_file else ""
    if not found and root and launch_dir and re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]*$", conversation or ""):
        found = transcript_model(transcript_path(root, launch_dir, conversation))
    return found


def main(argv):
    if len(argv) >= 2 and argv[1] == "settings" and len(argv) == 3:
        for key, value in settings(argv[2]).items():
            print(f"{key}={value}")
        return 0
    if len(argv) >= 2 and argv[1] == "hook" and len(argv) == 5:
        values = settings(argv[3])
        has_content = rewrite(argv[2], values["attribution"], argv[4])
        print(f"mode={values['attribution']}")
        print(f"model_trailer={values['model_trailer']}")
        print(f"content={'1' if has_content else '0'}")
        return 0
    if len(argv) >= 2 and argv[1] == "model" and len(argv) == 6:
        found = model(*argv[2:6])
        if found:
            print(found)
        return 0
    print((__doc__ or "").split("\n\n")[1], file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
